apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  namespace: kserve-test
spec:
  predictor:
    sklearn:
      # Ref: https://kserve.github.io/website/0.7/modelserving/storage/uri/uri/#specify-and-create-the-inferenceservice
      storageUri: "https://github.com/tduffy000/kfserving-uri-examples/blob/master/sklearn/frozen/model.joblib?raw=true"