apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kserve-manager-supplementary-role
rules:
- apiGroups: ["serving.kserve.io", "serving.knative.dev"]
  resources:
  - services
  - inferencegraphs
  - inferenceservices
  - trainedmodels
  - inferenceservices/status
  verbs:
  - get
  - list
  - create
  - update
- apiGroups: ["apps"]
  resources:
  - deployments
  verbs:
  - get
  - list
- apiGroups: ["networking.istio.io"]
  resources:
  - virtualservices
  verbs:
  - get
  - list
  - create
  - update
- apiGroups: [""]
  resources:
  - configmaps
  - events
  - pods
  - serviceaccounts
  - secrets
  - services
  verbs:
  - get
  - list
  - patch
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kserve-manager-supplementary-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kserve-manager-supplementary-role
subjects:
- kind: ServiceAccount
  name: kserve-controller-manager
  namespace: kserve